blank_issues_enabled: false
contact_links:
  - name: Paystack Community Support
    url: https://https://payslack.slack.com/
    about: Please join our Slack workspace for community support and discussions.